FROM arm64v8/alpine:3.6
MAINTAINER Shaun Crampton <shaun@tigera.io>

# Enable non-native builds of this image on an amd64 hosts.
# This must be positioned as the first executable command in this file! 
COPY  qemu-aarch64-static /usr/bin/qemu-aarch64-static

# Since our binary isn't designed to run as PID 1, run it via the tini init daemon.
RUN apk --no-cache add --update tini
ENTRYPOINT ["/sbin/tini", "--"]

# Install Felix's dependencies.
RUN apk --no-cache add ip6tables ipset iputils iproute2 conntrack-tools file

ADD felix.cfg /etc/calico/felix.cfg
ADD calico-felix-wrapper usr/bin

# Put out binary in /code rather than directly in /usr/bin.  This allows the downstream builds
# to more easily extract the Felix build artefacts from the container.
RUN mkdir /code
ADD bin/calico-felix /code
WORKDIR /code
RUN ln -s /code/calico-felix /usr/bin

# Run felix by default
CMD ["calico-felix-wrapper"]
